source 'https://rubygems.org'

gem 'sinatra', "2.1.0"
gem 'puma', "5.3.2"
gem 'sequel', "5.44.0"
gem 'sequel_pg', "1.14.0"
gem 'rack-throttle', "0.7.0"
gem 'public_suffix', "4.0.6"

group :test do
  gem 'rspec', "3.10.0"
  gem 'rack-test', "1.1.0"
end

